dataset: 'LLFF'
dateset_dir: '/home/sari/PycharmProjects/IPSM/dataset'
output_parent_dir: '/home/sari/PycharmProjects/IPSM/output'
exp_date: '260128'
exp_batch: 'third'
use_debug: False
n_views: 3
cuda_idx: 0
use_sd: False
use_wsds: True
use_wsds_2: True
use_sds: False
use_sdsi: False
use_lora: False
use_lora_2: False
use_pixel: True
use_color: True  # 颜色特征
use_litept: True
use_multi_scale_depth: True # 多尺度深度损失
use_multi_frature: True # 多尺度特征
use_cosine: True # 余弦退火
use_Dweight: True # 动态权重调整
use_gaussian_init: False # 高斯聚类初始化
use_OutlierFactor: False # 离群点筛选
use_dd_drop: False
use_dafe: False
use_SEBlock: True
se_type: 'improved'
use_unpool: False # 高斯反池化
use_fusionnet: False # 可学习的特征融合门控 (Learnable Gated Fusion)
use_scale_constraint: True # 深度一致性缩放约束
use_multi_view_consistency: True
rand_ply: False
origin: False
reset_param: 0.01 # origin 0.01
sh_interval: 500
sh_degree: 3  # 调整SH阶数，需与LitePT特征融合逻辑匹配
densify_grad_threshold: 0.0005
depth_weight: 0.05
depth_pseudo_weight: 0.5
opacity_reset_interval: 10000
lambda_dssim: 0.2
sample_pseudo_interval: 1
pixel_pseudo_weight: 2.5 # origin 2.0
sd_pseudo_weight: 0.5
warp_sds_pseudo_weight: 0.2
warp_sds_pseudo_weight_2: 2.0
sds_pseudo_weight: 1.0
resolution: 8
warp_sds_guidance_scale: 7.5

iterations: 10000
sd_guidance_scale: 7.5
num_inference_steps: 25
lora_start_iter: 2000
sd_guidance_start_iter: 2000
warp_sds_guidance_start_iter: 2000
pixel_guidance_start_iter: 2000
start_sample_pseudo : 2000

python_file: 'train.py'
